### PR TITLE
Fix rules section

### PR DESCRIPTION
**Pull request by baudehlo**
This fixes how you're supposed to write eslint plugins, and provides an example of a custom rule in case we ever want one.

### CODE REVIEW

**Comment by msimerson** [comment]
I'm not going to go read the docs again but if you're confident this is now the right way (and I'm heartened to hear there now **is** A Right Way), then full steam ahead!

**Comment by baudehlo** [comment]
Yeah the docs suck so learning it came out of writing a custom rule. I should probably patch the eslint docs but meh.

**Comment by msimerson** [comment]
Hey, at least they have docs now! Back when I did this plugin, the docs were, "look over there at how those guys did it."

**Comment by baudehlo** [comment]
Btw you're a rockstar doing all these updates. Thanks!

**Comment by baudehlo** [comment]
BTW I don't have permissions to publish this one.

**Comment by msimerson** [comment]
Try again. I just added you and Steve to the NPM profile.

**Comment by baudehlo** [comment]
Published.

**Pull request merged**
