### PR TITLE
SublimeLint breaks if you don't use full path

### PR DESCRIPTION
**Pull request by baudehlo**

### CODE REVIEW

**Comment by msimerson** [comment]
Interesting, SublimeLint works fine for me with the relative path.

**Comment by baudehlo** [comment]
It breaks (or broke) once you look at JS files in sub-folders - e.g. for
outbound split.

**Comment by msimerson** [comment]
I've got half a mind to just inline that (now very tiny) bit of JSON. I just can't remember if there was any good reason to leave it outside of index.js or not.

**Comment by baudehlo** [comment]
I don't even know why it's loaded. It's not used.

**Comment by msimerson** [comment]
It might be an anachronism from when all the rules were in that file. That line was probably there to make sure that the JSON file parsed correctly.

**Comment by Wesitos** [comment]
That line throws an exception when eslint is executed from a subdirectory (that's what flycheck does in emacs). Wouldn't it be better if we remove it?

**Pull request merged**
